# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50    
# Position Controllers ---------------------------------------
joint_s_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_1_s
  pid: {p: 100, i: 10, d: 0, i_clamp: 100}
joint_l_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_2_l
  pid: {p: 1000, i: 500, d: 0, i_clamp: 500}
joint_u_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_3_u
  pid: {p: 100, i: 10, d: 0, i_clamp: 100}
joint_r_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_4_r
  pid: {p: 10, i: 1, d: 0, i_clamp: 100}
joint_b_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_5_b
  pid: {p: 10, i: 1, d: 0, i_clamp: 100}  
joint_t_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_6_t
  pid: {p: 10, i: 1, d: 0, i_clamp: 100}
